In [ ]:
import numpy as np

original_regions_labels = np.array([['1', 'Frontal_left'],
 ['2', 'Frontal_right'],
 ['3', 'Motor_left'],
 ['4', 'Motor_right'],
 ['5', 'Somatosensory_left'],
 ['6', 'Somatosensory_right'],
 ['7', 'Auditory_left'],
 ['8', 'Auditory_right'],
 ['9', 'Visual_left'],
 ['10', 'Visual_right'],
 ['11', 'Retrosplenial_left'],
 ['12', 'Retrosplenial_right'],
 ['13', 'Temporal-Association_left'],
 ['14', 'Temporal-Association_right'],
 ['15', 'Visceral_left'],
 ['16', 'Visceral_right']]
)

regions = ["1", "2", "4", "6", "7"]

print(original_regions_labels[:,0])
print(regions)

x = np.isin(original_regions_labels[:,0], regions)
print(x)

final_regions_labels = np.array(original_regions_labels[x,:])
print(final_regions_labels)


def restrict_visible_regions(regions_labels, visible_regions):

    mask = np.isin(regions_labels[:,0], visible_regions)

    return np.array(original_regions_labels[x,:])

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16']
['1', '2', '4', '6', '7']
[ True  True False  True False  True  True False False False False False
 False False False False]
[['1' 'Frontal_left']
 ['2' 'Frontal_right']
 ['4' 'Motor_right']
 ['6' 'Somatosensory_right']
 ['7' 'Auditory_left']]


In [22]:
regions_dict = dict(original_regions_labels)
print(regions_dict)

{'1': 'Frontal_left', '2': 'Frontal_right', '3': 'Motor_left', '4': 'Motor_right', '5': 'Somatosensory_left', '6': 'Somatosensory_right', '7': 'Auditory_left', '8': 'Auditory_right', '9': 'Visual_left', '10': 'Visual_right', '11': 'Retrosplenial_left', '12': 'Retrosplenial_right', '13': 'Temporal-Association_left', '14': 'Temporal-Association_right', '15': 'Visceral_left', '16': 'Visceral_right'}


In [16]:
import numpy as np

regions = [['1', "bla"], ["2", "blabla"], ["3", "blablabla"]]
data = np.array([[[np.nan, 1, 2]], [[np.nan, 3, 4]], [[np.nan, 5, 6]]])

print(data.shape)
x = ~np.isnan(data[0,0,:])
y = np.where(x)[0]

print(x)
print(y)


keep_values = ~np.isnan(data[0,0,:])
keep_indices = np.where(keep_values)[0]
data = data[:,:,keep_indices]
regions = np.asarray(regions)[keep_indices,:].tolist()

print(data)
print(regions)



(3, 1, 3)
[False  True  True]
[1 2]
[[[1. 2.]]

 [[3. 4.]]

 [[5. 6.]]]
[['2', 'blabla'], ['3', 'blablabla']]
